= SignGenerator: Signs, Stamps, etc.

Program to make text strings into 3d shapes.
Can make signs of various sizes.
Can also make rubber stamps if you mirror the whole image
in the slicer, and print on TPU or similar filament.

== Usage & Caveats

Just run it. Either type your sign text into the text box,
pass strings (one quoted string per line) from the command line,
or, use File->Load to load the sign text from a ".txt" file.

Note: quite a few fonts have issues with one or another of the renderers,
so try different fonts and both renderers until something good comes up.
They may look funny when loaded into the slicer; slice them and look at the results before deciding.
Trial and error will be your friend.
Aside: the Gemini renderer has a hidden dependency on OpenJFX (JavaFX) so it will only work
on platforms where OpenJFX is supported.

== Lots more to do:

* Test out mkinstaller on Windoze and Linux platforms.
* Many Settings from Settings panel not actually honored.
** Settings: Defult load/save directory (~/signs)
* Load/save: Add confirming popup to be consistent.
* Optional border
* Optional rounded corners?
* Insert logos?
